---
#title: "Exercices : semaine IV"
# subtitle: "M1 ISIFAR MA1AY010"

# date: "2025-09-08"

format:
  latex:  
    output-file: cc3-miashs1et2-2025-A.tex
    documentclass: memoir
    classoption: [11pt, a4paper, twoside, article, titlepage=false]
    largemargins: false
    smallmargin: .5in         # outer margin (small).
    spinemargin: .5in
    include-in-header:
    #   - file: before_header_td.tex
      - text: |
          \makepagestyle{style-td1}
          \makeevenhead{style-td1}{\sffamily\small Intégration et Probabilités}{\sffamily B}{\sffamily\small CC III MIASHS 1 \& 2}
          \makeoddhead{style-td1}{\sffamily\small Intégration et Probabilités}{\sffamily B}{\sffamily\small CC III MIASHS 1 \& 2}
          \makeevenfoot{style-td1}{\sffamily\small MA1AY010}{\thepage}{\sffamily\small L3 MIASHS}
          \makeoddfoot{style-td1}{\sffamily\small L3 MIASHS}{\thepage}{\sffamily\small MA1AY010}
          \pagestyle{style-td1}
    include-before-body: 
      text: |
        \counterwithout{exercise}{section}

  pdf:
    output-file: cc3-miashs1et2-2025-A.pdf
    include-in-header:
    #   - file: before_header_td.tex
      - text: |
          \makepagestyle{style-td1}
          \makeevenhead{style-td1}{\sffamily\small Intégration et Probabilités}{\sffamily A}{\sffamily\small CC III MIASHS 1 \& 2}
          \makeoddhead{style-td1}{\sffamily\small Intégration et Probabilités}{\sffamily A}{\sffamily\small CC III MIASHS 1 \& 2}
          \makeevenfoot{style-td1}{\sffamily\small MA1AY010}{\thepage}{\sffamily\small L3 MIASHS}
          \makeoddfoot{style-td1}{\sffamily\small L3 MIASHS}{\thepage}{\sffamily\small MA1AY010}
          \pagestyle{style-td1}

engine: knitr
draft: true
---




```{r}
#| echo: false
#| warning: false
#| message: false

requireNamespace('quarto')
```







::: {.callout-note}

### CC III/IV  :    


- Licence MIASHS 
- 15 Décembre 2025   Durée : 1 heure 15 
- **Intégration et Probabilités** 

:::


::: {.content-visible when-profile="zorglub"  }

- Aide-mémoire : une feuille A4 recto verso autorisée
- Aucun autre document autorisé
- Aucun moyen de communication électronique autorisé

:::



::: {#exr-1-a   name=""} 


:::

::: {.callout-note name="Rappel"}

Dans cet exercice $\mathcal{N}(\mu, \Sigma)$ désigne la loi d'un vecteur gaussien d'espérance $\mu \in \mathbb{R}^d$ et de matrice de covariance $\Sigma$ à $d$ lignes et $d$ colonnes. 

:::

Dans cet exercice, $X = (X_1, X_2, X_3)^{\top} \sim \mathcal{N}(0, \Sigma)$ avec   

$$
\Sigma = 
  \begin{pmatrix} 
  1 & 1 & 1 \\ 
  1 & 2 & 2 \\ 
  1 & 2 & 3 \\ 
  \end{pmatrix}
$$


1. La loi de $X$ admet-elle une densité par rapport à la mesure de Lebesque sur $\mathbb{R}^3$ ? Si oui, donner cette densité.
1. Calculer la transformée de la Laplace de  la loi $X_3 - X_1$.
1. Calculer la densité conditionnelle de $X_3$ sachant $X_1=x_1$ et $X_2=x_2$ ?
1. Calculer l'espérance et la variance de  $X_1^2 + X_2^2$

::: {.content-visible when-profile="solution"}

::: {.callout-note title=Solution}

1. Oui, le déterminant de $\Sigma$ est 1, sa factorisation de Cholesky est :

    $$
    \Sigma = \begin{pmatrix} 
      1 & 0 & 0 \\ 
      1 & 1 & 0 \\ 
      1 & 1 & 1 \\ 
      \end{pmatrix} \times \begin{pmatrix} 
      1 & 1 & 1 \\ 
      0 & 1 & 1 \\ 
      0 & 0 & 1 \\ 
      \end{pmatrix}
    $$

1. $Z_3 - Z_1 \sim \mathcal{N}(0,2)$  donc $t \mapsto \exp\left(\frac{2t^2}{2}\right)$
1. Densité de $\mathcal{N}(x_2, 1)$
1. Espérance $3$ et variance $14$

:::

::: 



::: {#exr-3-a   name=""} 

:::



Dans cet exercice, $\lambda$ prend ses valeurs sur $]0, \infty)$,  $Z_{\lambda}$ est une variable aléatoire à valeur dans $\mathbb{N}$. Sa loi est définie par sa fonction génératrice 

$$G_\lambda(s) = \exp\left(\lambda \frac{s -1 }{1 - (1-p)s} \right)$$

pour $s \in [0,1]$, $\lambda>0$ et $p\in (0,1)$ 

1. Calculer la probabilité que $Z$ prenne les valeurs, $0$ et $1$
1. Calculer l'espérance de $Z$ (si finie)
1. Calculer la variance de $Z$ (si finie)
 
    *Maintenant $\lambda=1$, et $X_1, \ldots, X_n, \ldots \sim_{\text{i.i.d.}} G_1$ (distribuées selon la loi définie par $G_1$), et $S_n = \sum_{i=1}^n X_i$.*

1. Calculer la fonction génératrice de la loi de $S_n$
1. Étudier la convergence en probabilité de la suite $(S_n/n)_n$

::: {.content-visible when-profile="solution"}

::: {.callout-note title=Solution}

La loi de $Z$ est une distribution composée. $Z$ est distribuée comme $\sum_{i=1}^N X_i$ avec $N \sim \text{Poisson}(\lambda)$, $X_i \sim_{\text{i.i.d.}} \text{Geom}(p)$ et $N$ indépendant de $X_1, \ldots, X_i \ldots$. 

1. $P(Z=0)=P(N=0) \exp(-\lambda)$, $P(Z=1) = P(N=1 \text{ et } X_1=1) = \lambda p \exp(-\lambda)$
1. $\lambda/p$
1. $\lambda (1-p)/p^2$
1. $G_n$
1. Loi des grands nombres : tend vers $1/p$ en probabilité.

:::

:::


{{< pagebreak >}}

::: {#exr-5-a   name=""} 

:::

::: {.callout-note name="Rappel"}

Rappel: *La loi exponentielle de paramètre d'intensité $\lambda>0$ a pour densité $x \mapsto \mathbb{I}_{x>0} \lambda \exp(-\lambda x)$.*


:::


Dans cet exercice $Z_1, Z_2, Z_{1,2}$ sont trois variables indépendantes  distribuées selon des loi exponentielles d'intensités respectives $1, 1, 2$.

On définit,  $X = \min(Z_1, Z_{1,2})$ et $Y =  \min(Z_2, Z_{1,2})$. 

::::: {#marshall-olkin-ques}

1. Caractérisez la loi de $X$ (fonction de répartition, densité, fonction de survie).
1. Caractérisez la loi de $\min(X, Y)$
1. Quelle est la probabilité que $X=Y$ ?
1. $X$ et $Y$ sont-elles indépendantes ?
1. La loi jointe de $(X, Y)$ admet-elle une densité par rapport à la mesure de Lebesgue sur $\mathbb{R}^2$ ? Si oui, calculer la densité.
1. Calculer $P\{ X > a \text{ et } Y > b\}$ pour $a, b ∈ ]0,\infty)^2$
1. Calculer $P\{ X > a + s \text{ et } Y > b +s \mid X >a \text{ et } Y>b\}$ pour $a, b, s ∈ ]0,\infty)^2$ 



:::::


::: {.content-visible when-profile="solution"}

::: {.callout-note title=Solution}

::::: {#marshall-olkin-sol}

1. Exponentielle d'intensité $3$
1. Exponentielle d'intensité $4$ (et pas $6$)
1. $P\{X=Y\} = P\{ Z_{1,2} = \min(Z_1, Z_2, Z_{1,2})\} = \frac{2}{4}$.
1. Non (voir réponse aux deux questions précédentes)
1. Non (voir réponse à question 3)
1. $\exp\left(-a -b -2\max(a,b) \right)$
1. $P\{ X > s \text{ et } Y > s\}$

:::::




:::

:::
