---
#title: "Exercices : Mesures, Fonctions mesurables"
# subtitle: "M1 ISIFAR MA1AY010"

# date: "2026-09-08"

format:
  pdf:
    output-file: td2-2026.pdf
    include-in-header:
      - file: before_header_td.tex
      - text: |
          \copypagestyle{style-td1}{mystyle}
          \makeevenhead{style-td1}{\sffamily\small Probabilités et Extrêmes}{}{\sffamily\small TD II}
          \makeoddhead{style-td1}{\sffamily\small Probabilités et Extrêmes}{}{\sffamily\small TD II}
          \pagestyle{style-td1}

  html:
    output-file: td2-2026.html

engine: knitr
draft: false

categories: [Mesures, Fonctions mesurables, Probabilités]

---






```{r}
#| echo: false
#| warning: false
#| message: false

requireNamespace('quarto')
```

# Mesures et fonctions mesurables

## Détails

::: {#exr-mesure-positives name="Condition non-triviale"}

Dans la définition d'une mesure $\mu$ sur $(X, \mathcal{A})$, peut-on se passer de la condition $$\mu(\emptyset) = 0$$ ?

:::


::: {#exr-mesure-positives-2 name="Mesures positives étranges"}

Sur $(X, 2^X)$ on définit la fonction $\mu$ par $\mu(\emptyset) = 0$ et $\mu(A) = \infty$ pour toute partie non-vide $A$ de $X$.

$\mu$ est-elle $\sigma$-additive ? Est-ce une mesure ?

:::

## Mesures positives

::: {#exr-mesure-comptage name="Mesure de comptage"}

1. La fonction  de $2^{\mathbb{N}}$  dans $[0, \infty]$ qui à un ensemble $A \subseteq \mathbb{N}$ associe son cardinal $|A|$ est-elle une mesure positive sur $(\mathbb{N}, 2^{\mathbb{N}})$ ?
1. Dans la suite  $A_n$  désigne l'ensemble des multiples de $n$. Que vaut $|A_n|$ ?
1. On considère la suite croissantes des nombres *premiers* $p_1, p_2, \ldots, p_k, \ldots$ et $B_k =\cap_{j=1}^k A_{p_j}$. Que vaut $|B_k|$ ?
1. Que vaut $\cap_{k \in \mathbb{N}} B_k$ ?
1. A-t-on $\left| \lim_{k \to \infty} B_k \right| = \lim_{k \to \infty} \left|  B_k \right|$ ?

:::



<!-- ## Probabilités -->

<!-- ## Mesures $\sigma$-finies -->

<!-- Exercices 6, 7, 9 Chap. 1 Cohn -->


## Opérations sur les mesures

Dans cette sous-section $(X, \mathcal{A})$ est un espace mesurable ($\mathcal{A}$ est une tribu de parties de $X$).


::: {#exr-sigma-1 name="Sommes de mesures"}


Soit $(\mu_n)_n$ une suite  de mesures sur $(X, \mathcal{A})$.

On définit $\mu(A) = \sum_n \mu_n(A)$ pour $A \in \mathcal{A}$
 
1. $\mu$ est-elle une mesure sur   $(X, \mathcal{A})$ ?

:::

::: {#exr-sigma-2 name="Suites croissantes de mesures"}


Soit $(\mu_n)_n$ une suite croissante de mesures sur $(X, \mathcal{A})$ (pour tout $A \in \mathcal{A}$, tout $n \in \mathbb{N}$, $\mu_n(A) \leq \mu_{n+1}(A)$). 

On définit $\mu(A) =\lim_n \mu_n(A)$ pour $A \in \mathcal{A}$.

1. $\mu(A)$  est-elle bien définie pour tout $A \in \mathcal{A}$ ?
1. $\mu$ définit-elle une mesure sur $(X, \mathcal{A})$ ?


:::


::: {#exr-sigma-3 name="Sommes de Dirac"}

Dans cet exercice $\delta_x$ désigne la mesure de Dirac en $x \in \mathcal{R}$.

$$\delta_x(A) = \mathbb{I}_A(x) = \begin{cases} 1 & \text{si } x \in A \\ 0 & \text{sinon} \end{cases}$$




:::

::: {#exr-completion name="Complétion de mesure"}

Dans cet exercice $\mu$ est une mesure positive sur $\Omega, \mathcal{F}$. On souhaite étendre $\mu$ à des parties de $\Omega$ qui ne sont pas nécessairement dans $\mathcal{F}$.   

Si il existe $A_1, B_1$ tels que $A_1 ⊆ E ⊆ B_1$ avec $A_1, B_1 ∈ \mathcal{F}$  et $\mu(B_1 ⧵ A_1)=0$ alors $\mu(E) =\mu(A_1)$ par convention. 

1. Vérifier que cette définition n'aboutit pas à des contradictions.
1. Définir $\mathcal{G}$ l'ensemble des parties de ${X}$  pour lesquelles $\mu$ est définie. Vérifier que $\mathcal{G}$ est une tribu.
1. Vérifier que $\mu$ est une mesure sur $\mathcal{G}$. 

<!-- Théorème 1.36 dans Rudin. Real and Complex Analysis -->


:::

# Fonctions mesurables


## Propriétés

<!-- Stabilité par les opérations usuelles de l'analyse -->


<!-- 
::: {#exr-fontions-mesurables-1 name="Composition de fonctions mesurables"}

Soit $(X, \mathcal{A})$, $(Y, \mathcal{B})$ et $(Z, \mathcal{C})$ des espaces mesurables, $f: X \to Y$ et $g: Y \to Z$ des fonctions   $\mathcal{A}/\mathcal{B}$ et  $\mathcal{B}/\mathcal{C}$ mesurables.

Vérifier que $g \circ f$ est $\mathcal{A}/\mathcal{C}$ mesurable.

::: -->


::: {#exr-fontions-mesurables-2 name="Combinaisons linéaires de fonctions mesurables"}

Soit $(X, \mathcal{A})$ et $(Y, \mathcal{B})$ des espaces mesurables, $f$, $g$ deux fonctions $\mathcal{A}/\mathcal{B}$ mesurables et $\alpha$, $\beta$ deux réels.

Vérifier que $\alpha f + \beta g$ est $\mathcal{A}/\mathcal{B}$ mesurable.

:::


::: {#exr-fontions-mesurables-3 name="Produit de fonctions mesurables"}

Soit $(X, \mathcal{A})$ et $(Y, \mathcal{B})$ des espaces mesurables, $f$, $g$ deux fonctions $\mathcal{A}/\mathcal{B}$ mesurables.

Vérifier que $f \cdot g$ est $\mathcal{A}/\mathcal{B}$ mesurable.

:::

::: {#exr-fontions-mesurables-4 name="Limite simples de fonctions mesurables"}

Soit $(X, \mathcal{A})$ et $(Y, \mathcal{B})$ des espaces mesurables, $(f_n)_{n \in \mathbb{N}}$, $une suite de  fonctions $\mathcal{A}/\mathcal{B}$ mesurables, telle $\forall x \in X$, la suite $(f_n(x))_{n \in \mathbb{N}}$ converge vers une limite $f(x) \in Y$.

Vérifier que $f$ est $\mathcal{A}/\mathcal{B}$ mesurable.


:::


## Mesures image 


::: {#exr-image-1 name="Transformation affine"}

Soit $X$ une variable aléatoire réelle, dont la loi admet une densité $f$ par rapport à la mesure de Lebesgue. Soit $a$ un réel positif et $b$ un réel quelconque.


i. La loi de la variable aléatoire $aX +b$ admet-elle une densité ?
i. Si oui, exprimer cette densité en fonction de $f, a, b$.


:::






::: {#exr-image-2  name="CC1 2025"} 

Soit $X \sim \mathrm{U}(-\pi/2,\pi/2)$ (loi uniforme sur $[-\pi/2,\pi/2]$), on définit $Y =\cos(X)$.

i. La loi de $Y$ est-elle absolument continue?
i. Si oui, déterminer une version de sa densité.

:::

{{< pagebreak >}}

# Ensemble-mesure de Cantor

::: {#exr-cantor-1   name="Ensemble et mesure de Cantor"} 

Dans cet exercice, si $A \subseteq \mathbb{R}$ et $x \in \mathbb{R}$
on note 
$$x+ A = \left\{  x+y : y \in A \right\}$$
et 
$$x \times A = \left\{  xy : y \in A \right\}$$

Si on définit la suite de sous-ensembles de $[0,1]$, par la récursion suivante :

\begin{align*} 
C_1 & = 1/3 \times C_0 \cup 2/3 + 1/3\times C_0 \\
C_2 & = 1/3 \times C_1 \cup 2/3 + 1/3\times C_1 \\
\vdots & \quad \vdots \\
C_n & = 1/3 \times C_{n-1} \cup 2/3 + 1/3\times C_{n-1} \\
\vdots & = \vdots
\end{align*}  

alors $C = \cap_{n=1}^\infty C_n = \lim_{n \to \infty} C_n$.



(@) Les ensembles $C_n$ sont-ils ouverts/fermés/Boréliens ?
(@) L'ensemble $C$ est-il ouvert/fermé/Borélien ?
(@) $C$ est-il vide ?
(@) L'intérieur de $C$ est-il vide ? 
(@) Quelle est la mesure de Lebesgue de $C_n$ ?
(@) Quelle est la mesure de Lebesgue de $C$ ?


Pour chaque $n \in \mathbb{N}$, on note $P_n$ la loi uniforme sur $C_n$, et 
$F_n$ la fonction de répartition associée.

(@) Tracer le graphe de $F_n$ pour quelques valeurs de $n$ ($n=0, 1, 2, \ldots$).
(@) La fonction $F_n$ est-elle continue ? continue par morceaux ? 
(@) La fonction $F_n$ est-elle croissante ? strictement croissante ?
(@) Pouvez-vous evaluer/majorer $\sup_{x \in [0,1]} |F_n(x) - F_{n+1}(x)|$ ?
(@) Pour $A \in \mathcal{B}([0,1])$, que vaut $P_n(A)$ ?

On s'intéresse maintenant à la limite quand $n \to \infty$.

(@) La suite de fonctions $(F_n)_{n \in \mathbb{N}}$ converge-t-elle simplement ? uniformément ?
(@) Peut-on définir une limite pour $P_n(A)$ quand $n \to \infty$ ?
(@) Peut-on définir une loi de probabilité uniforme sur $C$?
(@) Si on répond oui à la question précédente :
    a. Quelle est la fonction de répartition de cette loi? 
    a. Est-elle continue? 
    a. Est-elle dérivable/ dérivable presque partout ? 
    a. Cette fonction de répartition est-elle l'intégrale de sa dérivée ?
(@) Soient $\{X_j, j \in \mathbb{N}^* \}$ une famille de variables i.i.d., distribuées suivant la loi de Bernoulli de paramètre $1/2$. On définit $X=2 \sum_{j \ge 1} \frac{X_j}{3^j}$. Quelle est la loi de $X$? 
(@) L'ensemble $C$ est-il dénombrable ?

:::


# Divers 


::: {#exr-divers-1   name="Les anniversaires"} 

On cherche a approximer la probabilité que parmi $N$ personnes, au moins deux (resp. trois) aient leur anniversaire le même jour. 

1. Pour $1 \le i <j \le N$, on note $E_{ij}$ l'événement que les personnes $i,j$ aient le même anniversaire. Quelle est la probabilité de $E_{ij}$? Dans la suite de l'exercice on omet de considérer le cas des $29$ février.  Que vaut alors $P(E_{ij})$? Montrer que les événements $E_{12}, E_{23}, E_{13}$ sont indépendants deux à deux, mais pas mutuellement indépendants. Exprimer la probabilité qu'il y ait au moins deux personnes qui aient leur anniversaire le même jour. 
1. Le but de cette question n'est pas d'obtenir un résultat exact, mais de faire une approximation assez bonne de la probabilité que parmi $N$ personnes, il y en ait au moins deux qui partagent le même anniversaire. On *admettra* donc que dans la suite on fait  *l'approximation* que les $\{E_{ij}, 1 \le i < j \le N\}$ sont mutuellement  indépendants. Quelle est alors la loi du nombre de couples ayant le même anniversaire? Approximer le résultat pour $N=30, N=60$.  
1. Par une méthode similaire, approximer la probabilité que parmi $60$ personnes, il y en ait au moins trois qui ont leur anniversaire le même jour. Finalement, approximer la probabilité de cet événement lorsque $N=90$. 

:::



::: {#exr-divers-2  name="Concentration"} 


Dans ce qui suit $||.||$ désigne la norme euclidienne. 

Pour $\varepsilon \in (0,1)$, $n \in \mathbb{N}$  
on note $A_{n, \varepsilon} := \{ x \in \mathbb{R}^n : (1-\varepsilon)(n/3)^{1/2} \le ||x|| \le (1+\varepsilon)(n/3)^{1/2}\}$, 
et $C_n=[-1,1]^n$. 

Montrer que pour tout $\varepsilon \in (0,1)$, la mesure de Lebesgue de $C_n \cap A_{n, \varepsilon}^c$ est négligeable, pour $n \to \infty$, devant celle de $C_n$.   

 *Indication* : On notera qu'un point générique dans $C_n$ a pour coordonnées $(X_1,...,X_n)$, avec $\{X_i, i \ge 1\}$ une famille de variables aléatoires i.i.d, uniformes sur $[-1,1]$.  

*Note* : Ceci signifie que pour $\varepsilon$ aussi petit qu'on souhaite le prendre, lorsque $n$ est grand, la majeure partie du volume de l'hypercube $C_n$ se trouve dans la couronne $A_{n,\varepsilon}$ (!) 

:::