---
#title: "Exercices : semaine II"
# subtitle: "M1 ISIFAR MA1AY010"

# date: "2026-09-08"

format:
  pdf:
    output-file: td5-2026.pdf
    include-in-header:
      - file: before_header_td.tex
      - text: |
          \copypagestyle{style-td1}{mystyle}
          \makeevenhead{style-td1}{\sffamily\small Probabilités et Extrêmes}{}{\sffamily\small TD V}
          \makeoddhead{style-td1}{\sffamily\small Probabilités et Extrêmes}{}{\sffamily\small TD V}
          \pagestyle{style-td1}

  html:
    output-file: td5-2026.html

engine: knitr
draft: false

categories: [Espérances, Moments]

---







```{r}
#| echo: false
#| warning: false
#| message: false

requireNamespace('quarto')
```

# Espérances et moments



::: {#exr-mediane-variationnelle name="Caractérisation de la médiane"}

Soit $X$ une variable aléatoire  réelle intégrable sur $(\Omega, \mathcal{F}, P)$. 
On suppose la loi de $X$ ($P \circ X^{-1}$) *diffuse*. 

On définit la fonction 
$$L(a) = a \mapsto \mathbb{E} \left| X - a\right| \, .$$

1. $H$ est-elle finie en tout $a$ ?
1. La fonction $L$ est-elle convexe ?
1. $H$ est-elle dérivable ?
1. Vérifier que les médianes de la loi de $X$ minimisent $L$. 

:::


## Inégalité de Lévy et variantes

::: {#exr-ineq-levy-2 name="SD et MAD"}

Soit $X$ une variable aléatoire réelle de carré intégrable et de loi diffuse. On note $m$ une médiane  de la loi de $X$. 

Vérifier que 

$$\underbrace{\mathbb{E}_P|X-m|}_{\text{MAD}}  \leq \underbrace{\sqrt{\operatorname{Var}_P(X)}}_{\text{SD}}$$

Sugestion: utiliser les conclusions de @exr-mediane-variationnelle. 

:::

::: {#exr-ineq-levy-1 name="Inégalité de Lévy"}


Soit $X$ une variable aléatoire réelle de carré intégrable et de loi diffuse. On note $m$ une médiane  de la loi de $X$. 

Vérifier que 

$$\left| \mathbb{E}_P X - m \right| \leq \sqrt{\operatorname{Var}_P(X)}$$

Sugestion: utiliser les conclusions de @exr-ineq-levy-2. 


:::


::: {#exr-ineq-levy-3 name="SD et IQR"}

Soit $X$ une variable aléatoire réelle de carré intégrable et de loi diffuse. On note $Q_1$ et $Q_3$ le premier et le troisième 
quartiles ($F^\leftarrow(1/4), F^\leftarrow(3/4)$, avec $F$  fonction de répartition de $P$ et $F^{\leftarrow}$ fonction quantile).
On note $Q_2 = F^\leftarrow(1/2)$ 

Comparer les indicateurs de dispersion :
$$\operatorname{IQR} =Q_3 -Q_1, \qquad \mathbb{E}_P|X-m|, \qquad \sqrt{\operatorname{Var}_P(X)}$$


:::


## Inégalités et applications 

::: {#exr-ineq-assoc name="Association"}

Dans cet exercice, $f$ et $g$ sont deux fonctions croissantes bornées, $X$ est une variable aléatoire sur $(\Omega, \mathcal{F}, P)$. 

Quels sont  les signes possibles de 
$$\mathbb{E}_P \left[f(X)g(X)\right] - \mathbb{E}_P \left[f(X)\right] \mathbb{E}_P \left[g(X)\right] \, .$$

:::



::: {#exr-gamma name="À propos de la fonction Gamma"}

La fonction $\Gamma$ est définie de $]0,\infty)$ vers $]0,\infty$ par 

$$\Gamma(x) = \int_0^\infty \mathrm{e}^{-t} t^{x-1} \mathrm{d}t$$

1. Verifier que $\int_0^\infty \mathrm{e}^{-t} t^{x-1} \mathrm{d}t$  est bien définie pour tout $x \in ]0, \infty)$. Vérifier que $\Gamma(x+1) = x\Gamma(x)$ pour $x>0$ et que $\Gamma(n+1) = n!$ pour $n \in \mathbb{N}$.
1. Montre que $\ln(\Gamma) = \ln \circ \Gamma$  est convexe. Suggestion: utiliser l'inégalité de Holder.
1. Montrer que $\Gamma$ est convexe.
1. Montrer que 
    $$\Gamma(x) = \lim_n \int_0^n t^{x-1} \left(1 -\frac{t}{n}\right)^n \mathrm{d}t$$ 
:::


::: {#exr-integrabilite-independance}

Montrer que si deux variables aléatoires $X$ et $Y$ sont indépendantes et intégrables alors $XY$ est intégrable. 

Peut-on se passer de l'hypothèse d'indépendance ?

:::


::: {#exr-indépendance-correlation}

Montrer que $X$ et $Y$ sont indépendantes si et seulement si pour toutes fonctions mesurables bornées $f$ et $g$, 
on a 
$$\mathbb{E}\left[f(X) g(Y)\right] = \mathbb{E}f(X) \times \mathbb{E}g(Y)$$

:::


::: {#exr-indépendance-correlation}

Montrer que pour toute fonction continuement dérivable strictement croissante  positive $f$ sur $[0, \infty)$, toute variable aléatoire positive $X$ sur  $(\Omega, \mathcal{F}, P)$:  

$$\mathbb{E}_P f(X) = \int_0^\infty f'(t)  P\{ X > t\} \mathrm{d}t + f(0)$$

:::


::: {#exr-}


:::