---
#title: "Exercices : semaine V"
# subtitle: "M1 ISIFAR MA1AY010"

# date: "2025-09-08"

format:
  pdf:
    output-file: td5.pdf
    include-in-header:
      - file: before_header_td.tex
      - text: |
          \copypagestyle{style-td1}{mystyle}
          \makeevenhead{style-td1}{\sffamily\small Probabilités et Extrêmes}{}{\sffamily\small TD V}
          \makeoddhead{style-td1}{\sffamily\small Probabilités et Extrêmes}{}{\sffamily\small TD V}
          \pagestyle{style-td1}

  html:
    output-file: td5.html

engine: knitr
draft: true
---




```{r}
#| echo: false
#| warning: false
#| message: false

requireNamespace('quarto')
```




```{r}
#| echo: false
#| eval: true

cnt_exo <- 1
```



::: {.callout-note}

### TD V : Convergences   

- 13 Octobre 2025-17 octobre 2025

- Master I ISIFAR

- **Probabilités** 

:::


::: {.callout-note}

### Loi des grands nombres 

:::

::: {#exr-1-1   name=""} 

:::









  
::: {.callout-note}

### Convergence en distribution

:::




::: {#exr-2-1   name=""} 

:::










