---
# title: "Exercices : semaine V"
# subtitle: "M1 ISIFAR MA1AY010"

# date: "2025-10-09"


format:
  pdf:
    output-file: td5-bis.pdf
    include-in-header:
      - file: before_header_td.tex
      - text: |
          \copypagestyle{style-td1}{mystyle}
          \makeevenhead{style-td1}{\sffamily\small Probabilités et Extrêmes}{}{\sffamily\small TD V.b}
          \makeoddhead{style-td1}{\sffamily\small Probabilités et Extrêmes}{}{\sffamily\small TD V.b}
          \pagestyle{style-td1}

  html:
    output-file: td5-bis.html


categories: [Convergences, Fourier, "Temps d'arrêt"]
engine: knitr
draft: false
---

```{r}
#| echo: false
#| warning: false
#| message: false

requireNamespace('quarto')
```


::: callout-note
### TD V : Caractérisations/Convergences

-   Octobre 2025

-   Master I ISIFAR

-   **Probabilités**
:::

::: {#exr-xxx  name=""}

:::

On définit la densité $f_a$ par $f_a(x) = \frac{a}{\pi(x^2 + a^2)}$ pour
$a>0$. Si $X \sim f_a, Y \sim f_b, X \perp\!\!\!\perp Y$ quelle est la
densité de la loi de $X+Y$?

*Suggestion: passez par les fonctions caractéristiques.*

::: {#exr-symetrique-arretee  name="Marche symétrique arrêtée"}

:::

On considère une suite de variables aléatoires $(X_n)_{n \geq 1}$ sur
$(\Omega,\mathcal{A},\mathbb{P})$ de loi
$\mathbb{P}(X_1=1)=1/2=1-\mathbb{P}(X_1=-1)$. On se donne un entier $x$
entre $0$ et $n$ et on pose pour $t\geq 1$, $S_t= x + \sum_{k=1}^t X_k$,
et $\tau_x=\inf\{t \geq 0, S_t=0 \text{ ou } S_t=n\}$. Le but de
l'exercice est de calculer $u_x=\mathbb{E}(\tau_x)$.

i.  $\tau_x$ est-elle une variable aléatoire?
ii. Calculer $u_0$ et $u_n$.
iii. Écrire une équation reliant $u_k$, $u_{k+1}$ et $u_{k-1}$.
iv. Poser $v_k=u_k-u_{k-1}$ et en déduire $u_k$, puis
    $\max_{k \in [0,n]} u_k$.
v.  Ecrire un *programme* permettant de simuler des réalisations
    aléatoires de $\tau_x$.
vi. Estimer *numériquement* les $u_k$ à partir des simulations de la
    question précédente.
vii. Représenter graphiquement les estimations de $u_k$ en fonction de
     $k$.


::: {#exr-weierstrass  name="Théorème d'approximation de Weierstrass"}

:::
Soit $f : [0, 1] → \mathbb{R}$ une fonction continue.

Soit $S_n$ une variable aléatoire distribuée selon une loi binomiale de
paramètres $n$ et $x \in (0,1)$.

Montrer que :

$$
\lim_n \sup_{0\leq x \leq 1} \left| f(x) - \sum_{k=0}^n \binom{n}{k} x^k  (1-x)^{n-k} f\left(\frac{k}{n}\right)\right| = 0 
$$

*Suggestion:* Utiliser $$
\mathbb{E}(Z) = \mathbb{E}(Z \mathbb{I}_A ) + \mathbb{E}(Z \mathbb{I}_{A^c} )
$$ avec $Z = f (x) − f (S_n/n )$ et $$
A = \{|S_n/n − x| > δ\}, 
$$

::: {.callout-note appearance="minimal"}
Le théorème d'approximation de Weierstrass s'énonce: toute fonction
continue sur $[0, 1]$ peut être approchée uniformément par des
polynômes.
:::

::: {.callout-note appearance="minimal"}
Si $f$ est une fonction croissante sur $[a,b]$, on définit son inverse
généralisée $f^\leftarrow$ par

$$f^{\leftarrow}(y) = \inf \{ x : x \in [a,b], \,  f(x) \geq y\} \qquad \text{ pour } y\in [ f(a),f(b)]\,.$$
:::

::: {#exr-quantiles-1  name="Fonctions quantiles"}

:::

i.  Montrer que si $(f_n)_n$ est une suite de fonctions croissantes sur
    $[a,b]\subset \mathbb{R}$ qui converge *simplement* vers $f$ une
    autre fonction croissante sur $[a,b]$ en tout point de continuité de
    $f$, alors la suite $(f_n^\leftarrow(y))$ converge simplement vers
    $f^\leftarrow(y)$ en tout $y\in [f(a),f(b)]$ où $f^\leftarrow$ est
    continue.

ii. Soit $F$ une fonction de répartition, on définit la fonction
    quantile associée $F^\leftarrow$ par

    $$F^{\leftarrow}(p) = \inf \{ x :  F(x) \geq p\} \qquad \text{ pour } p\in ]0,1[ \, .$$

    Vérifier que si deux fonctions de répartitions ont même fonction
    quantiles alors elles sont égales.

    Dans cette définition $F$ est une fonction de répartition,
    $F^\leftarrow$ la fonction quantile associée.

iii. Montrer que pour tout $x\in \mathbb{R}, p\in ]0,1[$,

<!-- -->

a.  $F^\leftarrow (p)\leq x \Leftrightarrow  p\leq F(x).$
b.  $F\circ F^\leftarrow(p) \geq p$ avec égalité si et seulement si il
    existe $x$ tel que $F(x)=p.$\\ Si $F\circ F^{\leftarrow}(p)>p$ alors
    $F^{\leftarrow}$ est discontinue en $p$.
c.  $F^\leftarrow\circ F(x)\leq  x$.\\ Si $F^\leftarrow\circ F(x)<  x$,
    alors il existe $\epsilon>0$ tel que $F(x-\epsilon)=F(x)$.
d.  $(F\circ G)^\leftarrow = G^\leftarrow \circ F^\leftarrow$

::: {#exr-stats-ordre-1  name="Statistiques d'ordre"}

:::

Si $Y_{1:n}\leq Y_{2:n}\leq\ldots\leq Y_{n:n}$ forme les statistiques
d'ordre d'un $n$-échantillon de la loi exponentielle d'espérance $1$, et
si $X_{1:n}\leq X_{2:n}\leq\ldots\leq X_{n:n}$ désigne les statistiques
d'ordre d'un $n$-échantillon d'une loi de fonction de répartition $F$
qui admet une densité partout positive, montrer que

$$\left( X_{1:n}, X_{2:n},\ldots, X_{n:n} \right) \sim \left(  F^\leftarrow (1-\exp(-Y_{1:n})),\ldots, F^\leftarrow(1-\exp(-Y_{n:n}))\right)\, .$$

La fonction quantile empirique $F_n^\leftarrow$ est la fonction quantile
associée à la fonction de répartition empirique $F_n$. Si les points de
l'échantillon sont deux à deux distincts

$$F_n^\leftarrow\left(p\right) = X_{k:n} \, \qquad \text{ pour }  \frac{k-1}{n}< p\leq \frac{k}{n} \, .$$

Soit $F$ une fonction de répartition qui est dérivable en
$F^{\leftarrow}(p)$ de dérivée non nulle notée $f(p)$ pour une valeur
$p\in ]0,1[$. Montrer que

$$\sqrt{n} \left( F_n^\leftarrow(p) -F^\leftarrow(p)\right) + \sqrt{n}\frac{1}{f(p)}\left(F_n(F^\leftarrow(p)) -p  \right) = o_P(1) \, . 
$$

Quelle est la loi limite de
$\sqrt{n} \left( F_n^\leftarrow(p) -F^\leftarrow(p)\right)$ ?

::: {#exr-convergences-1  name="Convergences (relations)"}

:::

Si $X_1, \ldots, X_n, \ldots$ sont définies sur le même espace
probabilisé, et convergent en distribution vers $Z$ (définie sur le même
espace), peut-on affirmer que :

i.  $X_1, \ldots, X_n, \ldots$ convergent en probabilité vers $Z$ ?
ii. $X_1, \ldots, X_n, \ldots$ convergent presque sûrement vers $Z$ ?

::: {#exr-proba-distrib  name="Convergence en distribution vers une constante"}

:::

Si $X_1, \ldots, X_n, \ldots$ sont définies sur le même espace
probabilisé, et convergent en distribution vers $c$ (une variable
aléatoire constante/dégénérée) égale à $c$ avec probabilité 1), montrer
que $X_1, \ldots, X_n, \ldots$ converge en probabilité vers $c$.

::: {#exr-slutsky  name="Lemme de Slutsky"}

:::

Si les suites de variables aléatoires $X_1, \ldots, X_n, \ldots$,
$Y_1, \ldots, Y_n, \ldots$ sont définies sur le même espace probabilisé,
et convergent respectivement en distribution vers $X$ et vers $c$
(constante), montrer que

i.  $X_nY_n \rightsquigarrow cX$
ii. $X_n/Y_n \rightsquigarrow X/c$ si $c\neq 0$
iii. $g(X_n, Y_n) \rightsquigarrow g(X,c)$ si
     $g : \mathbb{R}^2 \to \mathbb{R}$ est continue

<!-- Slutsky -->

::: {#exr-rep-mediane-unif  name="representation-mediane-uniforme"}


Dans cet exercice $Y_1, Y_2, \ldots, Y_{n+1}$ sont i.i.d.
exponentielles. On suppose $n$ impair montrer que 

$$\frac{\sum_{i=1}^{\lfloor(n+1)/2\rfloor} Y_i}{\sum_{i=1}^{n+1} Y_i}$$

est distribuée comme la médiane empirique d'un $n$-échantillon de la loi uniforme sur $[0,1]$. 

:::

::: {#exr-tcl-mediane-unif  name="tcl-mediane-uniforme"}

:::

Dans cet exercice $Y_1, Y_2, \ldots, Y_{n+1}$ sont i.i.d.
exponentielles.

i.  Montrer que

    $$\frac{\sum_{i=1}^{k} Y_i}{\sum_{i=1}^{n+1} Y_i}$$

    est distribué comme la $k^{\text{eme}}$ statistique d'ordre d'un $n$
    échantillon de ;la loi uniforme sur $[0,1]$

ii. Pour $n$ pair, $k=n/2$,

    $$\sqrt{n}\left(\frac{\sum_{i=1}^{k} Y_i}{\sum_{i=1}^{n+1} Y_i}- \frac{1}{2} \right)$$

    converge en distribution vers une Gaussienne centrée. Précisez la la
    variance de la loi limite.

    *Suggestion* : utilisez le lemme de Slutsky (@exr-slutsky).

::: {#exr-conv-densité  name="Lemme de Scheffé"}

:::

i.  Vérifier que la convergence simple des densités vers une densité
    implique la convergence en distribution.
ii. La réciproque est-elle vérifiée? A-t-elle un sens bien défini?

::: {#exr-conv-poisson  name="Convergence Poisson/Gaussienne"}

:::

Si $X_n \sim \text{Poisson}(n)$, montrer que
$\frac{X_n -n}{\sqrt{n}} \rightsquigarrow \mathcal{N}(0,1)$

::: {#exr-conv-gamma  name="Convergence Gamma/Gaussienne"}

:::

Si $X_n \sim \text{Gamma}(n,\lambda)$, montrer que
$\frac{X_n - n/\lambda}{\sqrt{n}} \rightsquigarrow \mathcal{N}(0,1/\lambda)$

::: {#exr-max-unif  name="Convergence Maxima d'échantillon uniforme"}

:::

Si $X_1, \ldots, X_n, \ldots \sim_{\text{i.i.d.}} \text{Unif}[0,1]$,
$M_n = \max(X_1, \ldots, X_n)$, pouvez-vous trouvez $(a_n, b_n)_n$ avec
$a_n >0$, tels que $\left((M_n -b_n)/a_n\right)_n$ convergent en loi
vers une variable aléatoire non-dégénérée?

::: {#exr-lfgn  name="Loi faible des grands nombres"}

:::

<!-- Loi faible des grands nombres avec moment d'ordre 4 sans troncature -->

Vérifier la loi faible des grands nombres si on suppose que les sommants
$X_i$ ont un moment d'ordre $4$.

