---
#title: "Exercices : semaine III"
# subtitle: "M1 ISIFAR MA1AY010"

# date: "2026-09-21"

format:
  pdf:
    output-file: td8-2026.pdf
    include-in-header:
      - file: before_header_td.tex
      - text: |
          \copypagestyle{style-td1}{mystyle}
          \makeevenhead{style-td1}{\sffamily\small Probabilités et Extrêmes}{}{\sffamily\small TD VIII}
          \makeoddhead{style-td1}{\sffamily\small Probabilités et Extrêmes}{}{\sffamily\small TD VIII}
          \pagestyle{style-td1}

  html:
    output-file: td8-2026.html

engine: knitr
draft: false

categories: [Caractérisations de lois, Fourier, Laplace]

---







```{r}
#| echo: false
#| warning: false
#| message: false

requireNamespace('quarto')
```

# Caractérisations de lois, Fourier, Laplace


## Transformée de Laplace 

::: {#exr-11  name="Transformées de Laplace utiles"}

Pour des valeurs de $t$ que l'on précisera, calculer la transformée de Laplace $L(t) := \mathbb{E}[\exp(-t X)]$ et la fonction génératrice des moments $G(u) := \mathbb{E}[u^X]$ de la variable $X$ dans les cas suivants. 

1. $X \sim \mathrm{Ber}(p)$, où $p \in [0,1]$, 
1. $X \sim \mathrm{Bin}(n,p)$, où $n \in \mathbb{N}^*, p \in [0,1]$,
1. $X \sim \mathrm{Geom}(p)$, où $p \in [0,1]$, 
1. $X \sim \mathrm{Poisson}(\lambda)$, où $\lambda>0$,  
1. $X=Y_1+...+Y_n$, où les $Y_i, 1 \le i \le n$ sont des variables indépendantes, et $Y_i \sim \mathrm{Poisson}(\lambda_i)$, avec $\lambda_i >0$.   

:::



:::  {#exr-size-biased  name="Distributions biaisées par la taille"}

Si $X$ est une variable aléatoire positive intégrable, la version *biaisée par la taille* de  $X$ est la variable aléatoire $X^*$ dont la loi $Q$ est absolument continue par rapport à celle de $X$ (notée $P$) et dont la densité (par rapport à celle de $X$)
est proportionnelle à $X$: 
$$
\frac{\mathrm{d}Q}{\mathrm{d}P}(x) = \frac{x}{\mathbb{E}X} \, .
$$

a. Caractériser $X^*$ lorsque $X$ est une Bernoulli.
a. Caractériser $X^*$ lorsque $X$ est binomiale.
a. Caractériser $X^*$ lorsque $X$ est Poisson.
a. Caractériser $X^*$ lorsque $X$ est Gamma.
a. Si $X$ est à valeurs entières, exprimer la fonction génératrice de $X^*$ en fonction de celle de $X$.
a. Exprimer la transformée de Laplace de $X^*$ en fonction de celle de $X$.
a. Si $U$ est une transformée de Laplace, dérivable à droite en $0$, $U'/U'(0)$ est-elle la
transformée de Laplace d'une loi sur $[0, \infty)$?

:::

{{< pagebreak >}}

## Fonctions caractéristiques


::: {#exr-trivial-charcfunc}

Soit la variable aléatoire réelle $X$ de loi $P$ et de fonction caractéristique $\widehat{F}$.

Vérifier les propriétés suivantes :

- $|\widehat{F}(t)|\leq 1$ pour tout $t\in \mathbb{R}$ ;
- $\widehat{F}(0)=1$
- Si $X$ est symétrique, $\widehat{F}$ est à valeurs réelles
- La fonction caractéristique de la loi de $a X +b$ est
    $$\mathrm{e}^{it b} \widehat{F}(at) \, .$$


:::


::: {#exr-quizz name="Quizz sur les fonctions caractéristiques"}

Si $\widehat{F}$ est la fonction caractéristique de la loi de $X$, et si $\epsilon \perp\!\!\!\perp X$, avec $P\{\epsilon=1\}= P\{\epsilon=-1\}=1/2$, quelle est la fonction caractéristique de la loi de $\epsilon X$?

:::

::: {#exr-charfunc-suual}

Calculer la fonction caractéristique de :

- la loi de Poisson de paramètre $\lambda>0$ ;
- la loi uniforme sur $[-1,1]$ ;
- la loi triangulaire sur $[-1,1]$ (densité : $1-|x|$ sur $[-1,1]$) ;
- la loi de Laplace, de densité $1/2 \exp(-|x|)$ ;
- la loi exponentielle de densité $\exp(-x)$ sur $[0,+\infty)$ ;

:::


::: {#exr-counter-example}

Donner un contre-exemple pour montrer que
$$
\Big(\forall t \in \mathbb{R}, \quad \widehat{F}_{X+Y}(t) =  \widehat{F}_X(t) \times \widehat{F}_Y(t) \Big)
\not\Rightarrow X \perp\!\!\!\perp Y \, .
$$

:::


::: {#exr-tent}

Vérifier que $\int_0^1 \cos(sx) (1-s) \mathrm{d}s\geq 0$ pour tout $x \in \mathbb{R}$.

*Indication :* Vérifier que $t \mapsto \int_0^1 \cos(tw) (1-w) \mathrm{d}w$ est la fonction caractéristique de la loi *tente*, de densité $(1-|w|)$ sur $[-1,1]$. Vérifier que cette fonction caractéristique est le carré du module d'une autre fonction caractéristique. 

:::


::: {#exr-density-convolution}

Vérifier que si $X$ et $Y$ sont indépendantes de densités $f_X$ et $f_Y$,
alors $f_X \star f_Y$ est une densité de la loi de $X+Y$.

:::


