---
title: "Syllabus"
---

[**Cliquer ici**](/documents/ma1au015-I-syllabus.pdf "PDF du syllabus") **pour télécharger une copie PDF du syllabus.**

## Informations 

|           | Jour       | Horaire              | Salle                       |
|-----------|-----------|-------------------|--------------------------------|
| Cours/Exercices  | Lundi     | 13:30 - 16:30  | Sophie Germain 2015      |
| Exercices | Mardi       | 8:30 - 10:30 | Halle aux Farines 227C |
| Cours/Exercices| Jeudi       | 13:30 - 16:30 | Sophie Germain 2015              |

##  Objectifs

A la fin du premier semestre, vous saurez...

-   Définir, caractériser une loi de probabilité sur un espace simple.
-   Établir et utiliser les différents types de convergence de variables aléatoires.
-   Manipuler les espérances conditionnelles.
-   Manipuler les vecteurs gaussiens (en dimension finie).

## Communauté

### Maser Mathématiques et Applications parcours  ISIFAR

As a student in this course, you have agreed to uphold the [Duke Community Standard](https://studentaffairs.duke.edu/conduct/about-us/duke-community-standard) as well as the practices specific to this course.

```{=html}
<iframe width="560" height="315" src="https://www.youtube.com/embed/_KN97j30ST4" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen>
</iframe>
```

### Accessibilité

If there is any portion of the course that is not accessible to you due to challenges with technology or the course format, please let me know so we can make appropriate accommodations.

The [Student Disability Access Office (SDAO)](https://access.duke.edu/students) is available to ensure that students are able to engage with their courses and related assignments.
Students should be in touch with the Student Disability Access Office to [request or update accommodations](https://access.duke.edu/requests) under these circumstances.

### Communication

All lecture notes, assignment instructions, an up-to-date schedule, and other course materials may be found on the course website at [sta210-s22.github.io/website](https://sta210-s22.github.io/website).

I will regularly send course announcements via email and Sakai, make sure to check one or the other of these regularly.
If an announcement is sent Monday through Thursday, I will assume that you have read the announcement by the next day.
If an announcement is sent on a Friday or over the weekend, I will assume that you have read it by Monday.

### Aide

-   If you have a question during lecture or lab, feel free to ask it! There are likely other students with the same question, so by asking you will create a learning opportunity for everyone.
-   The teaching team is here to help you be successful in the course. You are encouraged to attend office hours to ask questions about the course content and assignments. Many questions are most effectively answered as you discuss them with others, so office hours are a valuable resource. Please use them!
-   Outside of class and office hours, any general questions about course content or assignments should be posted on the course forum [Conversations](https://sakai.duke.edu/portal/site/779c3ebe-3b88-4bcc-bd01-1813e8396a23/tool/13b6446a-a6c6-4222-8cfb-c36d1f70802b). There is a chance another student has already asked a similar question, so please check the other posts in Conversations before adding a new question. If you know the answer to a question posted in the discussion forum, I encourage you to respond!
-   Emails should be reserved for questions not appropriate for the public forum. **If you email me, please include "STA 210" in the subject line.** Barring extenuating circumstances, I will respond to STA 210 emails within 48 hours Monday - Friday. Response time may be slower for emails sent Friday evening - Sunday.

Check out the [Support](/course-support.html) page for more resources.

## Bibliographie

While there is no official textbook for the course, we will be assigning readings from the following textbooks.


## Lessons et exercices

The goal of both the lectures and the labs is for them to be as interactive as possible.
My role as instructor is to introduce you new tools and techniques, but it is up to you to take them and make use of them.
A lot of what you do in this course will involve writing code, and coding is a skill that is best learned by doing.
Therefore, as much as possible, you will be working on a variety of tasks and activities throughout each lecture and lab.
You are expected to attend all lecture and lab sessions and meaningfully contribute to in-class exercises and discussion.
Additionally, some lectures will feature [application exercises] that will be graded.
In addition to application exercises will be periodic activities help build a learning community.
These will be short, fun activities that will help everyone in the class connect throughout the semester.


## Validation

Assessment for the course is comprised of six components: application exercises, homework assignments, labs, exams, projects, and teamwork.

### Exercices à préparer

Parts of some lectures will be dedicated to working on Application Exercises (AEs).
These exercises which give you an opportunity to practice apply the statistical concepts and code introduced in the readings and lectures.
These AEs are due within three days of the corresponding lecture period.
Specifically, AEs from Tuesday lectures are due Friday by 11:59 pm ET, and AEs from Thursday lectures are due Sunday by 11:59 pm ET.

Because these AEs are for practice, they will be graded based on completion, i.e., a good-faith effort has been made in attempting all parts.
Successful on-time completion of at least 80% of AEs will result in full credit for AEs in the final course grade.

### Contrôle continu

In labs, you will apply the concepts discussed in lecture to various data analysis scenarios, with a focus on the computation.
Most lab assignments will be completed in teams, and all team members are expected to contribute equally to the completion of each assignment.
You are expected to use the team's GitHub repository on the course's GitHub organization as the central platform for collaboration.
Commits to this repository will be used as a metric of each team member's relative contribution for each lab, and there will be periodic peer evaluation on the team collaboration.
Lab assignments will be completed using Quarto, correspond to an appropriate GitHub repository, and submitted for grading in Gradescope.

*The lowest lab grade will be dropped at the end of the semester.*


### Examens

There will be three, take-home, open-note exams.
Through these exams you have the opportunity to demonstrate what you've learned in the course thus far.
The exams will focus on the conceptual understanding of the content, and they may also include small analysis and computational tasks.
The content of the exam will be related to the content in the prepare, practice, and perform assignments.
More detail about the exams will be given during the semester.


## Notation

The final course grade will be calculated as follows:

| Category              | Percentage      |
|-----------------------|-----------------|
| Application exercises | 3%              |
| Homework              | 35% (7% x 5)    |
| Project               | 15%             |
| Lab                   | 14% (2.33% x 6) |
| Exam 01               | 10%             |
| Exam 02               | 10%             |
| Exam 03               | 10%             |

The final letter grade will be determined based on the following thresholds:

| Letter Grade | Final Course Grade |
|--------------|--------------------|
| A            | \>= 93             |
| A-           | 90 - 92.99         |
| B+           | 87 - 89.99         |
| B            | 83 - 86.99         |
| B-           | 80 - 82.99         |
| C+           | 77 - 79.99         |
| C            | 73 - 76.99         |
| C-           | 70 - 72.99         |
| D+           | 67 - 69.99         |
| D            | 63 - 66.99         |
| D-           | 60 - 62.99         |
| F            | \< 60              |

## Five tips for success

Your success on this course depends very much on you and the effort you put into it.
The course has been organized so that the burden of learning is on you.
Your TAs and I will help you be providing you with materials and answering questions and setting a pace, but for this to work you must do the following:

1.  Complete all the preparation work before class.
2.  Ask questions. As often as you can. In class, out of class. Ask me, ask the TAs, ask your friends, ask the person sitting next to you. This will help you more than anything else. If you get a question wrong on an assessment, ask us why. If you're not sure about the homework, ask. If you hear something on the news that sounds related to what we discussed, ask. If the reading is confusing, ask.
3.  Do the readings.
4.  Do the homework and lab.The earlier you start, the better. It's not enough to just mechanically plow through the exercises. You should ask yourself how these exercises relate to earlier material, and imagine how they might be changed (to make questions for an exam, for example.)
5.  Don't procrastinate. If something is confusing to you in Week 2, Week 3 will become more confusing, Week 4 even worse, and eventually you won't know where to begin asking questions. Don't let the week end with unanswered questions. But if you find yourself falling behind and not knowing where to begin asking, come to office hours, and let me help you identify a good (re)starting point.

## Course policies

### Intégrité

**TL;DR: Ne trichez pas!**

All students must adhere to the [Duke Community Standard (DCS)](https://trinity.duke.edu/undergraduate/academic-policies/community-standard-student-conduct): Duke University is a community dedicated to scholarship, leadership, and service and to the principles of honesty, fairness, and accountability.
Citizens of this community commit to reflect upon these principles in all academic and non-academic endeavors, and to protect and promote a culture of integrity.

To uphold the Duke Community Standard:

Students affirm their commitment to uphold the values of the Duke University community by signing a pledge that states:

-   I will not lie, cheat, or steal in my academic endeavors;
-   I will conduct myself honorably in all my endeavors;
-   I will act if the Standard is compromised

Regardless of course delivery format, it is your responsibility to understand and follow Duke policies regarding academic integrity, including doing one's own work, following proper citation of sources, and adhering to guidance around group work projects.
Ignoring these requirements is a violation of the Duke Community Standard.
If you have any questions about how to follow these requirements, please contact Jeanna McCullers ([jeanna.mccullers\@duke.edu](mailto:jeanna.mccullers@duke.edu)), Director of the Office of Student Conduct.


### Waiver for extenuating circumstances

If there are circumstances that prevent you from completing a lab or homework assignment by the stated due date, you may email [Dr. Çetinkaya-Rundel](mailto:mc301@duke.edu) **and** our head TA [Rick Presman](mailto:rick.presman@duke.edu) before the deadline to waive the late penalty.
In your email, you only need to request the waiver; you do not need to provide explanation.
This waiver may only be used for once in the semester, so only use it for a truly extenuating circumstance.

If there are circumstances that are having a longer-term impact on your academic performance, please let your academic dean know, as they can be a resource.
Please let Dr. Çetinkaya-Rundel know if you need help contacting your academic dean.

### Regrade request policy

Regrade requests must be submitted on Gradescope within a week of when an assignment is returned.
Regrade requests will be considered if there was an error in the grade calculation or if you feel a correct answer was mistakenly marked as incorrect.
Requests to dispute the number of points deducted for an incorrect response will not be considered.
Note that by submitting a regrade request, the entire question will be graded which could potentially result in losing points.

*No grades will be changed after the final project presentations.*

### Assiduité

Responsibility for class attendance rests with individual students.
Since regular and punctual class attendance is expected, students must accept the consequences of failure to attend.
More details on Trinity attendance policies are available [here](https://trinity.duke.edu/undergraduate/academic-policies/class-attendance-and-missed-work).

However, there may be many reasons why you cannot be in class on a given day, particularly with possible extra personal and academic stress and health concerns this semester.
All course lectures will be recorded and available to enrolled students after class.
If you miss a lecture, make sure to watch the recording and review the material before the next class session.
Lab time is dedicated to working on your lab assignments and collaborating with your teammates on your project.
If you miss a lab session, make sure to communicate with your team about how you can make up your contribution.
Given the technologies we use in the course, this is straightforward to do asynchronously.
If you know you're going to miss a lab session and you're feeling well enough to do so, notify your teammates ahead of time.
Overall these policies are put in place to ensure communication between team members, respect for each others' time, and also to give you a safety net in the case of illness or other reasons that keep you away from attending class.


## Sauvez les dates


-   **Janvier**: Examen (session 1)


Cliquer [ici](https://edt.math.univ-paris-diderot.fr/#/parcours/math/m1) for l'emploi du temps.
