---
title: "MA15Y010  Probabilités et Extrêmes"
tbl-colwidths: [5,10,30,5,5,5,5,5,5,5]
date: '2025-09-19'
---

Cette page résume le déroulement du semestre


::: column-screen-inset-right
|   Semaine            | Date        | Thème(s)   |  Préparer  |        Cours   |   Exercices     |  Évaluation |                      
|:--------------------:|-------------|------------|:----------:|:--------------:|:---------------:|:-----------:|
|  [1](/weeks/week-1.html)  | 8 Sep 2025 |    Révisions Licence         |           |         |  [TD 1](/exercices/td1.qmd)                                                                                                                |                   |
|   | 9 Sep  |   Révisions Licence     |            |         |      [TD 1](/exercices/td1.qmd)           |                   |
|   | 11 Sep  | Révisions Licence: théoremes de convergence (intégration)  |            |         |                                                                                                          [TD 1](/exercices/td1.qmd)       |                   |
|  [2](/weeks/week-2.html)  | 15 Sep  |  Révisions Licence: Espaces roduits          |            |         |                                                                                                                 |                   |
|   | 16 Sep  | Changement de variables. Calcul Gamma/Beta           |            |         |                                                                                                                 |                   |
|   | 18 Sep  | Fonctions génératrices/Conditionnement discret  |            |         |   
|  [3](/weeks/week-3.html)  | 22 Sep  |  Moments, Espaces $L^p$      |            |         |        [TD 3](/exercices/td3.qmd)                                                                                                         |                   |
|   | 23 Sep  | Espérance conditionnelle           |            |         |                                                                                                                  |                   |
|   | 25 Sep  | Conditionnement  |            |         |  [TD 2](/exercices/td2.qmd) [TD 2 supplément](/exercices/td2-supplement.qmd) | |
|  [4](/weeks/week-4.html)  | 29 Sep  |  Caractérisations       |            |         |                                                                                                             [TD4](/exercices/td4.qmd)     |                   |
|   | 30 Sep  |  Caractérisations              |            |         |                                                                       [Corrections TD1](/corriges/td1.html)                                          |                   |
|   | 2 Oct  |     Caractérisations    |            |         |  [Corrections TD3](/corriges/td3.html)  | |
|  [5](/weeks/week-5.html)  | 6 Oct   |  Convergences       |            |         |    TD 5                                                                                                             |                   |
|   | 7  Oct  | CC 1           |            |         |                                                                                                                 |                   |
|   | 9 Oct  |  Convergences  |            |         |   
|  [6](/weeks/week-6.html)  | 13 Oct   |  Convergences      |            |         |                                                                                                                 |                   |
|   | 14  Oct  |   Vecteurs gaussiens          |            |         |                                                                                                             TD 6     |                   |
|   | 16 Oct  |  Vecteurs gaussiens  + CC 2  |            |         |
:::