---
title: "Semaine 1"
subtitle: "Bienvenue"
editor: source
---

::: callout-important

La semaine I (8-12 septembre 2025)  est consacrée aux révisions de Licence. On (re)-présentera beaucoup de définitions, quelques
outils essentiels, et on tentera d'utiliser ces définitions et outils sur la liste d'exercices des feuilles de TD.   

:::

## Préparer/Revoir

- Espace probabilisable 
  - Tribu/$\sigma$-algèbre
  - Tribu borélienne
  - Tribu de Lebesgue
  - Lemme des classes monotones
- Loi de probabilité, mesure positive, $\sigma$-additivité
- Fonctions mesurables et variables aléatoires
- Espérance, variance, moments
- Théorèmes de convergence (monotone, Fatou, dominée)
- Indépendance (Évenements, Tribus)

## Exercices

[Feuille TD I](/exercices/td1.html)

Corrigés : 

- 1 (transformation affine), 
- 2 (minima, maxima), 
- 10 (transformées de Laplace), 
- 11 (densité de la loi du carré), 
- 17 (somme de Poisson indépendantes, conditionnement discret), 
- 18 (sommes aléatoires de variables indépendantes).

## Exercices supplémentaires

[Feuille TD I suppléments](/exercices/td1-supplement.html)



<br><br>

::: {style="font-size: 0.875em;"}
Retour à [l'agenda](/ "Course schedule") ⏎
:::
